### ISSUE TITLE
无法正常地被slimefun加载

### ISSUE THREAD

**Issue by stydxm** [StarWishsama/ExoticGarden-CN#12]
![CM )2LPT_ 2Y)KJK~K R4O8](https://user-images.githubusercontent.com/62790279/104030367-4375b100-5206-11eb-8766-e8734d6db578.png)
exotic garden和slime fun应该都是最新版，还是掉插件

**Comment by StarWishsama** [comment]
见 https://github.com/StarWishsama/Slimefun4/commit/26714d9ad286c62f93f3f709e5c2c9b68818e8ef
