### ISSUE TITLE
树可以破坏末地的传送门

### ISSUE THREAD

**Issue by stydxm** [StarWishsama/ExoticGarden-CN#2]
在原作者那里提过了，半天没反应，只能来这里了（更具体的说明在[这里](https://github.com/TheBusyBiscuit/ExoticGarden/issues/125)）

树木生长会破坏末地的传送门（回主世界的那个），从主世界去末地的不清楚

![GMbDpV.gif](https://s1.ax1x.com/2020/03/31/GMbDpV.gif)

GIF看不到的话[点这里](https://s1.ax1x.com/2020/03/31/GMbDpV.gif)

**Comment by StarWishsama** [comment]
看gif的话应该都是会破坏的

**Comment by stydxm** [comment]
> 
> 
> 看gif的话应该都是会破坏的

嗯，但是我没试过，不敢说一定就行，原版的树我试了会被挡住
