### ISSUE TITLE
是否考虑在近期汉化支持1.18的版本

### ISSUE THREAD

**Issue by FTPam** [StarWishsama/ExoticGarden-CN#29]
感谢StarWishsama的汉化工作
英文原版似乎已经添加了对1.18的支持，地址：https://thebusybiscuit.github.io/builds/TheBusyBiscuit/ExoticGarden/master/
请问是否考虑在近期汉化最新build。

**Comment by StarWishsama** [comment]
本仓库已停止更新
可以前往 https://github.com/GuizhanCraft/ExoticGarden-CN/
