### ISSUE TITLE
后台报错

### ISSUE THREAD

**Issue by 1600496156** [StarWishsama/ExoticGarden-CN#8]
![1](https://user-images.githubusercontent.com/62275587/89702633-d7043680-d975-11ea-88f9-a56a20b22137.PNG)
![2](https://user-images.githubusercontent.com/62275587/89702636-d9669080-d975-11ea-816e-924969c26880.PNG)
[报错log.txt](https://github.com/StarWishsama/ExoticGarden-CN/files/5044666/log.txt)

**Comment by StarWishsama** [comment]
已适配
